apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
spec:
  project: infrastructure
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 7.5.0
    helm:
      parameters:
        - name: metrics.enabled
          value: 'true'
        # - name: metrics.serviceMonitor.enabled
        #   value: 'true'
    chart: nginx-ingress-controller
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: nginx-ingress
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
