apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo
  namespace: argocd
spec:
  project: apps
  source:
    repoURL: 'https://stefanprodan.github.io/podinfo'
    targetRevision: 5.0.1
    helm:
      values: |
        replicaCount: 10
        cache: "redis-master.redis:6379"
        ingress:
          enabled: "true"
          annotations:
            kubernetes.io/ingress.class: "nginx"
          path: "/"
          hosts:
            - "podinfo.jamesmcleod.xyz"        
    chart: podinfo
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: podinfo
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true


# ingress:
#   enabled: false
#   annotations: {}
#     # kubernetes.io/ingress.class: nginx
#     # kubernetes.io/tls-acme: "true"
#   path: /*
#   hosts: []
# #    - podinfo.local
#   tls: []
#   #  - secretName: chart-example-tls
#   #    hosts:
#   #      - chart-example.local
